### ISSUE TITLE
NPE on announcement when arena is empty

### ISSUE THREAD

**Issue by tomkeuper** [tomkeuper/BedWars1058#142]
**Describe the bug**
Announcements dont get cleaned up after an arena is finished

**To Reproduce**

**Log**
[23:29:37 WARN]: [BedWars2023] Plugin BedWars2023 v1.0-SNAPSHOT generated an exception while executing task 4967
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "com.tomkeuper.bedwars.arena.Arena.getPlayers()" is null
        at com.tomkeuper.bedwars.arena.Announcement$1.run(Announcement.java:53) ~[bedwars-plugin-1.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Expected Behaviour**
Clean up announcements after an arena is finished.

**System (please complete the following information):**
 - OS: Linux
 - Server software Purpur
 - Server Version 1.19.4
 - Plugin Version 1.0-dev

**Comment by tomkeuper** [comment]
fixed with 89d419ddae5644f50186f55a0b00924245041f45
